sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t tlzzs/docker-react ./client


script:
  - docker run -e CI=true tlzzs/docker-react npm run test -- --coverage

after_success:
  - docker build -t stephengrider/multi-client ./client
  - docker build -t stephengrider/multi-nginx ./nginx
  - docker build -t stephengrider/multi-server ./server
  - docker build -t stephengrider/multi-worker ./worker